from google.cloud import firestore
from datetime import datetime, timezone, timedelta

def check_recent_changes():
    db = firestore.Client()
    
    # Get time ranges
    now = datetime.now(timezone.utc)
    fifteen_mins_ago = now - timedelta(minutes=15)
    one_hour_ago = now - timedelta(hours=1)
    
    print("=== Recent Word Additions ===")
    words_ref = db.collection('words')
    
    # Check last 15 minutes
    recent_words = words_ref.where('created_at', '>', fifteen_mins_ago).stream()
    print("\nWords added in last 15 minutes:")
    fifteen_min_count = 0
    for word in recent_words:
        fifteen_min_count += 1
        word_data = word.to_dict()
        print(f"\nWord: {word.id}")
        print(f"Created at: {word_data.get('created_at')}")
        print(f"Status: {word_data.get('status')}")
        print(f"Generated by: {word_data.get('generated_by', 'unknown')}")
    
    # Check last hour
    hour_words = words_ref.where('created_at', '>', one_hour_ago).stream()
    hour_count = sum(1 for _ in hour_words)
    
    print(f"\nSummary:")
    print(f"Words added in last 15 minutes: {fifteen_min_count}")
    print(f"Total words added in last hour: {hour_count}")
    
    # Check words by status
    print("\nWords by Status:")
    for status in range(1, 5):
        status_words = words_ref.where('status', '==', status).stream()
        count = sum(1 for _ in status_words)
        print(f"Status {status}: {count} words")

if __name__ == "__main__":
    check_recent_changes()